import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "pl" | "uk";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "uk",
  setLang: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>("uk");

  const t = (key: string): string => {
    const translations = allTranslations[lang];
    return (translations as Record<string, string>)[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

const allTranslations: Record<Language, Record<string, string>> = {
  uk: {
    // Top bar
    "nav.news": "Новини",
    "nav.exhibitions": "Виставки",
    "nav.contact_person": "Контактна особа",
    "nav.worldwide": "По всьому світу",
    // Main nav
    "nav.company": "КОМПАНІЯ",
    "nav.products": "ПРОДУКТИ",
    "nav.service": "СЕРВІС",
    "nav.contact": "КОНТАКТ",
    "nav.menu": "Меню",
    // Search
    "search.placeholder": "Пошук...",
    "search.open": "Відкрити пошук",
    "search.close": "Закрити пошук",
    "search.submit": "Шукати",
    // Hero
    "hero.tagline1": "ДИСПЕРГУВАННЯ ▪ ЗМІШУВАННЯ ▪ ПОДРІБНЕННЯ",
    "hero.tagline2": "МАШИНИ ДЛЯ ЛАКОФАРБОВОЇ ТА ХІМІЧНОЇ ПРОМИСЛОВОСТІ",
    // About
    "about.title": "ТЕОН представляється",
    "about.text1": "Машинобудівний завод Теон у Мелле-Нойєнкірхені перебуває у власності родини з моменту заснування у 1889 році. Як виробник високоякісних машин для лакофарбової та хімічної промисловості, компанія Теон може спиратися на більш ніж 130-річний досвід.",
    "about.text2": "Високоякісні машини для диспергування, змішування та подрібнення серії KREI використовуються у виробництві фарб, лаків, чорнил, клеїв, косметики та багатьох інших галузях хімічної промисловості.",
    // Products
    "products.title": "НАШІ ПРОДУКТИ",
    "products.more": "Детальніше",
    // Why Teon
    "why.title": "ЧОМУ ТЕОН?",
    "why.since": "З 1889 року",
    "why.since.desc": "Понад 130 років досвіду у машинобудуванні",
    "why.quality": "Німецька якість",
    "why.quality.desc": "Найвищі стандарти виготовлення та контролю якості",
    "why.worldwide": "По всьому світу",
    "why.worldwide.desc": "Поставки та сервіс у більш ніж 50 країнах світу",
    "why.innovation": "Інновації",
    "why.innovation.desc": "Постійний розвиток та вдосконалення технологій",
    // News
    "news.title": "НОВИНИ",
    "news.all": "Всі новини",
    "news.read_more": "Читати далі",
    // Exhibitions
    "exhibitions.title": "ВИСТАВКИ",
    // Footer
    "footer.rights": "© 2024 Теон. Усі права захищені.",
    // Company page
    "company.title": "КОМПАНІЯ",
    "company.about": "Про нас",
    "company.history": "Історія компанії",
    "company.contact_info": "Контактна інформація",
    "company.certificates": "Сертифікати",
    // Products page
    "products.page.title": "ПРОДУКТИ",
    "products.request": "Запросити інформацію",
    "products.features": "Характеристики:",
    "products.models": "Моделі:",
    // Service page
    "service.title": "СЕРВІС",
    "service.our": "Наш сервіс",
    "service.text": "Компанія Теон пропонує повний спектр сервісних послуг для свого обладнання. Наші спеціалісти готові надати підтримку на всіх етапах — від монтажу та пуско-налагодження до планового технічного обслуговування та ремонту.",
    "service.cta": "Потрібна допомога?",
    "service.cta.text": "Зв'яжіться з нашою службою технічної підтримки",
    "service.contact_us": "Зв'язатися з нами",
    // Service items
    "service.item.install.title": "Монтаж та пуско-налагодження",
    "service.item.install.text": "Кваліфіковані техніки Теон здійснять монтаж та налагодження обладнання на вашому підприємстві.",
    "service.item.maintenance.title": "Технічне обслуговування",
    "service.item.maintenance.text": "Регулярне технічне обслуговування для забезпечення надійної роботи обладнання та максимального терміну служби.",
    "service.item.repair.title": "Ремонт та відновлення",
    "service.item.repair.text": "Оперативний ремонт будь-якої складності з використанням оригінальних запчастин Теон.",
    "service.item.spares.title": "Запасні частини",
    "service.item.spares.text": "Широкий асортимент оригінальних запасних частин на складі, швидка доставка по всьому світу.",
    "service.item.training.title": "Навчання персоналу",
    "service.item.training.text": "Навчання операторів та технічного персоналу на підприємстві або на нашому навчальному центрі у Хюллгорсті.",
    "service.item.support.title": "Технічна підтримка",
    "service.item.support.text": "Цілодобова технічна підтримка для вирішення будь-яких питань по телефону або онлайн.",
    // Contact page
    "contact.title": "КОНТАКТ",
    "contact.info": "Контактна інформація",
    "contact.write": "Написати нам",
    "contact.name": "Ім'я *",
    "contact.company": "Компанія",
    "contact.email": "Email *",
    "contact.phone": "Телефон",
    "contact.subject": "Тема *",
    "contact.message": "Повідомлення *",
    "contact.send": "Надіслати повідомлення",
    "contact.success": "Дякуємо за ваше повідомлення!",
    "contact.success.text": "Ми зв'яжемося з вами найближчим часом.",
    "contact.required": "* Обов'язкові поля",
    "contact.subject.product": "Запит на продукт",
    "contact.subject.service": "Запит на сервіс",
    "contact.subject.parts": "Запасні частини",
    "contact.subject.general": "Загальне питання",
    "contact.subject.other": "Інше",
    "contact.subject.select": "Оберіть тему...",
    // Product detail
    "product.back": "← Назад до продуктів",
    "product.request": "Запросити пропозицію",
    "product.download": "Завантажити каталог",
    "product.applications": "Застосування",
    "product.technical": "Технічні характеристики",
    "product.features": "Особливості",
    "product.models": "Серія моделей",
    "product.contact_expert": "Зв'язатися з експертом",
    "breadcrumb.home": "Головна",
    "breadcrumb.products": "Продукти",
    // Gallery
    "gallery.title": "Галерея",
    "gallery.description": "Тут буде представлено наші роботи, фото та відео з виробництва, монтажу та сервісу обладнання.",
    "gallery.photo": "Фото",
    // Quick links / cards
    "quick.service.title": "Сервіс",
    "quick.service.desc": "Технічна підтримка та обслуговування",
    "quick.contact.title": "Контактна особа",
    "quick.contact.desc": "Знайдіть вашого менеджера",
    "quick.gallery.title": "Галерея",
    "quick.gallery.desc": "Перегляньте нашу роботу",
  },

  en: {
    "nav.news": "News",
    "nav.exhibitions": "Exhibitions",
    "nav.contact_person": "Contact Person",
    "nav.worldwide": "Worldwide",
    "nav.company": "COMPANY",
    "nav.products": "PRODUCTS",
    "nav.service": "SERVICE",
    "nav.contact": "CONTACT",
    "nav.menu": "Menu",
    "search.placeholder": "Search...",
    "search.open": "Open search",
    "search.close": "Close search",
    "search.submit": "Submit search",
    "hero.tagline1": "DISPERSING ▪ MIXING ▪ GRINDING",
    "hero.tagline2": "MACHINES FOR THE PAINT AND CHEMICAL INDUSTRY",
    "about.title": "Introducing Teon",
    "about.text1": "Teon's machine factory in Melle-Neuenkirchen has been family-owned since its founding in 1889. As a manufacturer of high-quality machines for the paint and chemical industry, Teon can draw on more than 130 years of experience.",
    "about.text2": "High-quality machines for dispersing, mixing and grinding of the KREI series are used in the production of paints, varnishes, inks, adhesives, cosmetics and many other branches of the chemical industry.",
    "products.title": "OUR PRODUCTS",
    "products.more": "Learn More",
    "why.title": "WHY TEON?",
    "why.since": "Since 1889",
    "why.since.desc": "More than 130 years of experience in mechanical engineering",
    "why.quality": "German Quality",
    "why.quality.desc": "Highest manufacturing and quality control standards",
    "why.worldwide": "Worldwide",
    "why.worldwide.desc": "Delivery and service in more than 50 countries",
    "why.innovation": "Innovation",
    "why.innovation.desc": "Continuous development and improvement of technologies",
    "news.title": "NEWS",
    "news.all": "All News",
    "news.read_more": "Read More",
    "exhibitions.title": "EXHIBITIONS",
    "footer.rights": "© 2024 Teon. All rights reserved.",
    "company.title": "COMPANY",
    "company.about": "About Us",
    "company.history": "Company History",
    "company.contact_info": "Contact Information",
    "company.certificates": "Certificates",
    "products.page.title": "PRODUCTS",
    "products.request": "Request Information",
    "products.features": "Features:",
    "products.models": "Models:",
    "service.title": "SERVICE",
    "service.our": "Our Service",
    "service.text": "Teon offers a full range of service for its equipment. Our specialists are ready to provide support at all stages — from installation and commissioning to scheduled maintenance and repair.",
    "service.cta": "Need Help?",
    "service.cta.text": "Contact our technical support team",
    "service.contact_us": "Contact Us",
    // Service items
    "service.item.install.title": "Installation & Commissioning",
    "service.item.install.text": "Qualified Teon technicians will install and commission the equipment at your facility.",
    "service.item.maintenance.title": "Maintenance",
    "service.item.maintenance.text": "Regular maintenance to ensure reliable equipment operation and maximum service life.",
    "service.item.repair.title": "Repair & Restoration",
    "service.item.repair.text": "Prompt repair of any complexity using original Teon spare parts.",
    "service.item.spares.title": "Spare Parts",
    "service.item.spares.text": "Wide range of original spare parts in stock, fast delivery worldwide.",
    "service.item.training.title": "Staff Training",
    "service.item.training.text": "Training of operators and technical staff at your site or at our training center in Hüllhorst.",
    "service.item.support.title": "Technical Support",
    "service.item.support.text": "Round-the-clock technical support for any questions by phone or online.",
    "contact.title": "CONTACT",
    "contact.info": "Contact Information",
    "contact.write": "Write to Us",
    "contact.name": "Name *",
    "contact.company": "Company",
    "contact.email": "Email *",
    "contact.phone": "Phone",
    "contact.subject": "Subject *",
    "contact.message": "Message *",
    "contact.send": "Send Message",
    "contact.success": "Thank you for your message!",
    "contact.success.text": "We will contact you within the next business hours.",
    "contact.required": "* Required fields",
    "contact.subject.product": "Product Inquiry",
    "contact.subject.service": "Service Request",
    "contact.subject.parts": "Spare Parts",
    "contact.subject.general": "General Question",
    "contact.subject.other": "Other",
    "contact.subject.select": "Select subject...",
    "product.back": "← Back to Products",
    "product.request": "Request a Quote",
    "product.download": "Download Catalog",
    "product.applications": "Applications",
    "product.technical": "Technical Specifications",
    "product.features": "Features",
    "product.models": "Model Range",
    "product.contact_expert": "Contact an Expert",
    "breadcrumb.home": "Home",
    "breadcrumb.products": "Products",
    // Gallery
    "gallery.title": "Gallery",
    "gallery.description": "Here we will showcase our work — photos and videos of production, installation and service of equipment.",
    "gallery.photo": "Photo",
    // Quick links / cards
    "quick.service.title": "Service",
    "quick.service.desc": "Technical support and maintenance",
    "quick.contact.title": "Contact Person",
    "quick.contact.desc": "Find your account manager",
    "quick.gallery.title": "Gallery",
    "quick.gallery.desc": "View our work",
  },

  pl: {
    "nav.news": "Aktualności",
    "nav.exhibitions": "Targi",
    "nav.contact_person": "Osoba kontaktowa",
    "nav.worldwide": "Na całym świecie",
    "nav.company": "FIRMA",
    "nav.products": "PRODUKTY",
    "nav.service": "SERWIS",
    "nav.contact": "KONTAKT",
    "nav.menu": "Menu",
    "search.placeholder": "Szukaj...",
    "search.open": "Otwórz wyszukiwarkę",
    "search.close": "Zamknij wyszukiwarkę",
    "search.submit": "Szukaj",
    "hero.tagline1": "DYSPERGOWANIE ▪ MIESZANIE ▪ MIELENIE",
    "hero.tagline2": "MASZYNY DLA PRZEMYSŁU LAKIERNICZEGO I CHEMICZNEGO",
    "about.title": "Teon przedstawia się",
    "about.text1": "Fabryka maszyn Teon w Melle-Neuenkirchen jest własnością rodziny od momentu jej założenia w 1889 roku. Jako producent wysokiej jakości maszyn dla przemysłu lakierniczego i chemicznego, firma Teon może opierać się na ponad 130-letnim doświadczeniu.",
    "about.text2": "Wysokiej jakości maszyny do dyspergowania, mieszania i mielenia serii KREI są stosowane w produkcji farb, lakierów, tuszy, klejów, kosmetyki i wielu innych gałęziach przemysłu chemicznego.",
    "products.title": "NASZE PRODUKTY",
    "products.more": "Dowiedz się więcej",
    "why.title": "DLACZEGO TEON?",
    "why.since": "Od 1889 roku",
    "why.since.desc": "Ponad 130 lat doświadczenia w budowie maszyn",
    "why.quality": "Niemiecka jakość",
    "why.quality.desc": "Najwyższe standardy produkcji i kontroli jakości",
    "why.worldwide": "Na całym świecie",
    "why.worldwide.desc": "Dostawa i serwis w ponad 50 krajach świata",
    "why.innovation": "Innowacje",
    "why.innovation.desc": "Ciągły rozwój i doskonalenie technologii",
    "news.title": "AKTUALNOŚCI",
    "news.all": "Wszystkie aktualności",
    "news.read_more": "Czytaj dalej",
    "exhibitions.title": "TARGI",
    "footer.rights": "© 2024 Teon. Wszelkie prawa zastrzeżone.",
    "company.title": "FIRMA",
    "company.about": "O nas",
    "company.history": "Historia firmy",
    "company.contact_info": "Dane kontaktowe",
    "company.certificates": "Certyfikaty",
    "products.page.title": "PRODUKTY",
    "products.request": "Zapytaj o informacje",
    "products.features": "Cechy:",
    "products.models": "Modele:",
    "service.title": "SERWIS",
    "service.our": "Nasz serwis",
    "service.text": "Firma Teon oferuje pełen zakres usług serwisowych dla swoich urządzeń. Nasi specjaliści są gotowi zapewnić wsparcie na wszystkich etapach — od montażu i uruchomienia po planową konserwację i naprawy.",
    "service.cta": "Potrzebujesz pomocy?",
    "service.cta.text": "Skontaktuj się z naszym działem wsparcia technicznego",
    "service.contact_us": "Skontaktuj się z nami",
    // Service items
    "service.item.install.title": "Montaż i uruchomienie",
    "service.item.install.text": "Wykwalifikowani technicy Teon przeprowadzą montaż i uruchomienie urządzeń w Twoim zakładzie.",
    "service.item.maintenance.title": "Konserwacja",
    "service.item.maintenance.text": "Regularna konserwacja zapewniająca niezawodne działanie urządzeń i maksymalną żywotność.",
    "service.item.repair.title": "Naprawa i regeneracja",
    "service.item.repair.text": "Sprawna naprawa o dowolnym stopniu złożoności z użyciem oryginalnych części zamiennych Teon.",
    "service.item.spares.title": "Części zamienne",
    "service.item.spares.text": "Szeroki asortyment oryginalnych części zamiennych na stanie, szybka dostawa na cały świat.",
    "service.item.training.title": "Szkolenie personelu",
    "service.item.training.text": "Szkolenie operatorów i personelu technicznego u klienta lub w naszym centrum szkoleniowym w Hüllhorst.",
    "service.item.support.title": "Wsparcie techniczne",
    "service.item.support.text": "Całodobowe wsparcie techniczne w rozwiązywaniu wszelkich problemów przez telefon lub online.",
    "contact.title": "KONTAKT",
    "contact.info": "Dane kontaktowe",
    "contact.write": "Napisz do nas",
    "contact.name": "Imię i nazwisko *",
    "contact.company": "Firma",
    "contact.email": "Email *",
    "contact.phone": "Telefon",
    "contact.subject": "Temat *",
    "contact.message": "Wiadomość *",
    "contact.send": "Wyślij wiadomość",
    "contact.success": "Dziękujemy za wiadomość!",
    "contact.success.text": "Skontaktujemy się z Tobą w najbliższym czasie roboczym.",
    "contact.required": "* Pola wymagane",
    "contact.subject.product": "Zapytanie o produkt",
    "contact.subject.service": "Zapytanie serwisowe",
    "contact.subject.parts": "Części zamienne",
    "contact.subject.general": "Ogólne pytanie",
    "contact.subject.other": "Inne",
    "contact.subject.select": "Wybierz temat...",
    "product.back": "← Powrót do produktów",
    "product.request": "Zapytaj o ofertę",
    "product.download": "Pobierz katalog",
    "product.applications": "Zastosowania",
    "product.technical": "Dane techniczne",
    "product.features": "Cechy szczególne",
    "product.models": "Seria modeli",
    "product.contact_expert": "Skontaktuj się z ekspertem",
    "breadcrumb.home": "Strona główna",
    "breadcrumb.products": "Produkty",
    // Gallery
    "gallery.title": "Galeria",
    "gallery.description": "Tutaj zaprezentujemy nasze realizacje, zdjęcia i filmy z produkcji, montażu i serwisu urządzeń.",
    "gallery.photo": "Zdjęcie",
    // Quick links / cards
    "quick.service.title": "Serwis",
    "quick.service.desc": "Wsparcie techniczne i konserwacja",
    "quick.contact.title": "Osoba kontaktowa",
    "quick.contact.desc": "Znajdź swojego opiekuna",
    "quick.gallery.title": "Galeria",
    "quick.gallery.desc": "Zobacz nasze realizacje",
  },
};
