import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "pl" | "uk";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "uk",
  setLang: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>("uk");

  const t = (key: string): string => {
    const translations = allTranslations[lang];
    return (translations as Record<string, string>)[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

const allTranslations: Record<Language, Record<string, string>> = {
  uk: {
    "nav.news": "Новини",
    "nav.exhibitions": "Виставки",
    "nav.contact_person": "Контактна особа",
    "nav.worldwide": "По всьому світу",
    "nav.company": "КОМПАНІЯ",
    "nav.products": "ПРОДУКТИ",
    "nav.service": "СЕРВІС",
    "nav.contact": "КОНТАКТ",
    "nav.quote": "ОТРИМАТИ КП",
    "nav.menu": "Меню",
    "search.placeholder": "Пошук...",
    "search.open": "Відкрити пошук",
    "search.close": "Закрити пошук",
    "search.submit": "Шукати",
    "search.title": "Результати пошуку",
    "search.for": 'Результати для "{query}"',
    "search.no_results": "Нічого не знайдено",
    "search.no_results_desc": "Спробуйте змінити пошуковий запит або перегляньте наші продукти.",
    "search.browse_products": "Переглянути всі продукти",
    "search.found": "Знайдено {count} результатів",
    "hero.tagline1": "ДИСПЕРГУВАННЯ ▪ ЗМІШУВАННЯ ▪ ПОДРІБНЕННЯ",
    "hero.tagline2": "МАШИНИ ДЛЯ ЛАКОФАРБОВОЇ ТА ХІМІЧНОЇ ПРОМИСЛОВОСТІ",
    "process.title": "НАШІ ТЕХНОЛОГІЇ",
    "process.dispersing": "Диспергування",
    "process.dispersing.desc": "Ефективне диспергування пігментів та наповнювачів у рідких системах для досягнення максимальної якості кольору та стабільності.",
    "process.mixing": "Змішування",
    "process.mixing.desc": "Точне змішування багатокомпонентних рецептур із забезпеченням гомогенності по всьому об'єму резервуара.",
    "process.grinding": "Подрібнення",
    "process.grinding.desc": "Тонке мокре подрібнення до субмікронних розмірів для отримання ідеально гладких покриттів та високої покривної здатності.",
    "about.title": "ТЕОН представляється",
    "about.text1": "ТОВ «ТЕОН УКРАЇНА» — офіційний представник високоякісного обладнання Teon в Україні. Ми надаємо повний спектр рішень для диспергування, змішування та подрібнення, а також сервісних послуг для підприємств лакофарбової та хімічної промисловості.",
    "about.text2": "За 8 років роботи ми встановили понад 200 машин, побудували мережу сервісних центрів і заслужили довіру провідних підприємств України. Наша місія — забезпечити українську промисловість сучасним обладнанням з повноцінною технічною підтримкою.",
    "products.title": "НАШІ ПРОДУКТИ",
    "products.more": "Детальніше",
    "why.title": "ЧОМУ ТЕОН?",
    "why.since": "З 2017 року",
    "why.since.desc": "8+ років досвіду на ринку України",
    "why.quality": "Європейська якість",
    "why.quality.desc": "Найвищі стандарти виготовлення та контролю якості",
    "why.worldwide": "По всьому світу",
    "why.worldwide.desc": "Поставки та сервіс у більш ніж 50 країнах світу",
    "why.innovation": "Інновації",
    "why.innovation.desc": "Постійний розвиток та вдосконалення технологій",
    "news.title": "НОВИНИ",
    "news.all": "Всі новини",
    "news.read_more": "Читати далі",
    "exhibitions.title": "ВИСТАВКИ",
    "footer.rights": "© 2024 Теон. Усі права захищені.",
    "company.title": "КОМПАНІЯ",
    "company.about": "Про нас",
    "company.history": "Історія компанії",
    "company.contact_info": "Контактна інформація",
    "company.certificates": "Сертифікати",
    "products.page.title": "ПРОДУКТИ",
    "products.request": "Запросити інформацію",
    "products.features": "Характеристики:",
    "products.models": "Моделі:",
    "service.title": "СЕРВІС",
    "service.our": "Наш сервіс",
    "service.text": "Компанія Теон пропонує повний спектр сервісних послуг для свого обладнання. Наші спеціалісти готові надати підтримку на всіх етапах — від монтажу та пуско-налагодження до планового технічного обслуговування та ремонту.",
    "service.cta": "Потрібна допомога?",
    "service.cta.text": "Зв'яжіться з нашою службою технічної підтримки",
    "service.contact_us": "Зв'язатися з нами",
    "service.item.install.title": "Монтаж та пуско-налагодження",
    "service.item.install.text": "Кваліфіковані техніки Теон здійснять монтаж та налагодження обладнання на вашому підприємстві.",
    "service.item.maintenance.title": "Технічне обслуговування",
    "service.item.maintenance.text": "Регулярне технічне обслуговування для забезпечення надійної роботи обладнання та максимального терміну служби.",
    "service.item.repair.title": "Ремонт та відновлення",
    "service.item.repair.text": "Оперативний ремонт будь-якої складності з використанням оригінальних запчастин Теон.",
    "service.item.spares.title": "Запасні частини",
    "service.item.spares.text": "Широкий асортимент оригінальних запасних частин на складі, швидка доставка по всьому світу.",
    "service.item.training.title": "Навчання персоналу",
    "service.item.training.text": "Навчання операторів та технічного персоналу на підприємстві або на нашому навчальному центрі у Хюллгорсті.",
    "service.item.support.title": "Технічна підтримка",
    "service.item.support.text": "Цілодобова технічна підтримка для вирішення будь-яких питань по телефону або онлайн.",
    "contact.title": "КОНТАКТ",
    "contact.info": "Контактна інформація",
    "contact.write": "Написати нам",
    "contact.name": "Ім'я *",
    "contact.company": "Компанія",
    "contact.email": "Email *",
    "contact.phone": "Телефон",
    "contact.subject": "Тема *",
    "contact.message": "Повідомлення *",
    "contact.send": "Надіслати повідомлення",
    "contact.success": "Дякуємо за ваше повідомлення!",
    "contact.success.text": "Ми зв'яжемося з вами найближчим часом.",
    "contact.required": "* Обов'язкові поля",
    "contact.subject.product": "Запит на продукт",
    "contact.subject.service": "Запит на сервіс",
    "contact.subject.parts": "Запасні частини",
    "contact.subject.general": "Загальне питання",
    "contact.subject.other": "Інше",
    "contact.subject.select": "Оберіть тему...",
    "product.back": "← Назад до продуктів",
    "product.request": "Запросити пропозицію",
    "product.download": "Завантажити каталог",
    "product.applications": "Застосування",
    "product.technical": "Технічні характеристики",
    "product.features": "Особливості",
    "product.models": "Серія моделей",
    "product.contact_expert": "Зв'язатися з експертом",
    "breadcrumb.home": "Головна",
    "breadcrumb.products": "Продукти",
    "gallery.title": "Галерея",
    "gallery.description": "Тут буде представлено наші роботи, фото та відео з виробництва, монтажу та сервісу обладнання.",
    "gallery.photo": "Фото",
    "quick.service.title": "Сервіс",
    "quick.service.desc": "Технічна підтримка та обслуговування",
    "quick.contact.title": "Контактна особа",
    "quick.contact.desc": "Знайдіть вашого менеджера",
    "quick.gallery.title": "Галерея",
    "quick.gallery.desc": "Перегляньте нашу роботу",
    "hero.quote_btn": "Отримати КП",
    "hero.catalog_btn": "Каталог продукції",
    "hero.consultation_btn": "Консультація",
    "hero.trust_iso": "ISO 9001:2015",
    "hero.trust_atex": "ATEX",
    "hero.trust_ce": "CE",
    "hero.trust_text": "Сертифікована європейська якість",
    "testimonials.title": "ВІДГУКИ КЛІЄНТІВ",
    "testimonial.1.text": "Обладнання KREI значно підвищило продуктивність нашого виробництва. Якість диспергування перевершила наші очікування.",
    "testimonial.1.name": "Петро Коваленко",
    "testimonial.1.company": "ТОВ «Промфарб»",
    "testimonial.2.text": "Сервісне обслуговування та підтримка Теон на найвищому рівні. Рекомендуємо як надійного партнера.",
    "testimonial.2.name": "Андреас Шнайдер",
    "testimonial.2.company": "Farben GmbH",
    "testimonial.3.text": "Високоточне обладнання, яке повністю відповідає нашим вимогам. Особливо відзначаємо надійність та довговічність.",
    "testimonial.3.name": "Марта Новак",
    "testimonial.3.company": "Chemia Sp. z o.o.",
    "stats.machines": "Машин встановлено",
    "stats.clients": "Клієнтів",
    "stats.years": "Років досвіду",
    "quote.title": "ОТРИМАТИ КП",
    "quote.subtitle": "Залиште заявку — і ми надішлемо вам комерційну пропозицію протягом 24 годин",
    "quote.name": "Ім'я *",
    "quote.email": "Email *",
    "quote.message": "Повідомлення *",
    "quote.send": "Надіслати запит",
    "quote.success": "Дякуємо за запит!",
    "quote.success.text": "Ми зв'яжемося з вами найближчим часом.",
    "quote.required": "* Обов'язкові поля",
    "product.feedback_title": "Отримати консультацію",
    "product.feedback_desc": "Залиште свої контакти — наш менеджер зв'яжеться з вами протягом 24 годин",
    "product.feedback_name": "Ваше ім'я *",
    "product.feedback_phone": "Телефон *",
    "product.feedback_email": "Email",
    "product.feedback_comment": "Коментар (модель, об'єм, потужність...)",
    "product.feedback_send": "Відправити запит",
    "product.feedback_success": "Дякуємо!",
    "product.feedback_success_text": "Ми зв'яжемося з вами найближчим часом.",
    "product.feedback_via": "Або зв'яжіться з нами напряму:",
    "product.media_title": "Фото та відео реальної роботи",
    "product.media_desc": "Подивіться, як обладнання KREI працює на реальних виробничих майданчиках",
    "product.media_request": "Запитати фото/відео",
    "product.media_request_text": "Хочете побачити більше матеріалів? Надішліть запит — і ми поділимося деталями.",
    "product.media_video_title": "Відео роботи",
    "product.comparison_title": "Порівняння моделей",
    "home.about_short": "ТОВ «ТЕОН УКРАЇНА» — офіційний представник високоякісного європейського обладнання Teon в Україні. За 8 років — понад 200 машин та 50+ країн.",
    "home.about_link": "Дізнатися більше про компанію",
    "trust.quality": "Європейська якість",
    "trust.global": "Понад 50 країн",
    "trust.experience": "8+ років досвіду",
    "trust.certified": "Сертифіковано",
  },
  en: {
    "nav.news": "News",
    "nav.exhibitions": "Exhibitions",
    "nav.contact_person": "Contact Person",
    "nav.worldwide": "Worldwide",
    "nav.company": "COMPANY",
    "nav.products": "PRODUCTS",
    "nav.service": "SERVICE",
    "nav.contact": "CONTACT",
    "nav.quote": "REQUEST A QUOTE",
    "nav.menu": "Menu",
    "search.placeholder": "Search...",
    "search.open": "Open search",
    "search.close": "Close search",
    "search.submit": "Submit search",
    "search.title": "Search Results",
    "search.for": 'Results for "{query}"',
    "search.no_results": "Nothing found",
    "search.no_results_desc": "Try changing your search query or browse our products.",
    "search.browse_products": "Browse all products",
    "search.found": "Found {count} results",
    "hero.tagline1": "DISPERSING ▪ MIXING ▪ GRINDING",
    "hero.tagline2": "MACHINES FOR THE PAINT AND CHEMICAL INDUSTRY",
    "process.title": "OUR TECHNOLOGIES",
    "process.dispersing": "Dispersing",
    "process.dispersing.desc": "Efficient dispersion of pigments and fillers in liquid systems to achieve maximum color quality and stability.",
    "process.mixing": "Mixing",
    "process.mixing.desc": "Precise mixing of multi-component formulations ensuring homogeneity throughout the entire vessel volume.",
    "process.grinding": "Grinding",
    "process.grinding.desc": "Fine wet grinding down to submicron sizes for perfectly smooth coatings and high hiding power.",
    "about.title": "Introducing Teon",
    "about.text1": "TEON UKRAINE LLC is the official representative of high-quality Teon equipment in Ukraine. We provide a full range of solutions for dispersing, mixing and grinding, as well as services for the paint and chemical industries.",
    "about.text2": "Over 8 years, we have installed over 200 machines, built a network of service centers, and earned the trust of leading Ukrainian enterprises. Our mission is to provide Ukrainian industry with modern equipment with full technical support.",
    "products.title": "OUR PRODUCTS",
    "products.more": "Learn More",
    "why.title": "WHY TEON?",
    "why.since": "Since 2017",
    "why.since.desc": "8+ years of experience in the Ukrainian market",
    "why.quality": "European Quality",
    "why.quality.desc": "The highest manufacturing and quality control standards",
    "why.worldwide": "Worldwide",
    "why.worldwide.desc": "Delivery and service in more than 50 countries",
    "why.innovation": "Innovation",
    "why.innovation.desc": "Continuous development and improvement of technologies",
    "news.title": "NEWS",
    "news.all": "All News",
    "news.read_more": "Read More",
    "exhibitions.title": "EXHIBITIONS",
    "footer.rights": "© 2024 Teon. All rights reserved.",
    "company.title": "COMPANY",
    "company.about": "About Us",
    "company.history": "Company History",
    "company.contact_info": "Contact Information",
    "company.certificates": "Certificates",
    "products.page.title": "PRODUCTS",
    "products.request": "Request Information",
    "products.features": "Features:",
    "products.models": "Models:",
    "service.title": "SERVICE",
    "service.our": "Our Service",
    "service.text": "Teon offers a full range of service for its equipment. Our specialists are ready to provide support at all stages — from installation and commissioning to scheduled maintenance and repair.",
    "service.cta": "Need Help?",
    "service.cta.text": "Contact our technical support team",
    "service.contact_us": "Contact Us",
    "service.item.install.title": "Installation & Commissioning",
    "service.item.install.text": "Qualified Teon technicians will install and commission the equipment at your facility.",
    "service.item.maintenance.title": "Maintenance",
    "service.item.maintenance.text": "Regular maintenance to ensure reliable equipment operation and maximum service life.",
    "service.item.repair.title": "Repair & Restoration",
    "service.item.repair.text": "Prompt repair of any complexity using original Teon spare parts.",
    "service.item.spares.title": "Spare Parts",
    "service.item.spares.text": "Wide range of original spare parts in stock, fast delivery worldwide.",
    "service.item.training.title": "Staff Training",
    "service.item.training.text": "Training of operators and technical staff at your site or at our training center in Ukraine.",
    "service.item.support.title": "Technical Support",
    "service.item.support.text": "Round-the-clock technical support for any questions by phone or online.",
    "contact.title": "CONTACT",
    "contact.info": "Contact Information",
    "contact.write": "Write to Us",
    "contact.name": "Name *",
    "contact.company": "Company",
    "contact.email": "Email *",
    "contact.phone": "Phone",
    "contact.subject": "Subject *",
    "contact.message": "Message *",
    "contact.send": "Send Message",
    "contact.success": "Thank you for your message!",
    "contact.success.text": "We will contact you within the next business hours.",
    "contact.required": "* Required fields",
    "contact.subject.product": "Product Inquiry",
    "contact.subject.service": "Service Request",
    "contact.subject.parts": "Spare Parts",
    "contact.subject.general": "General Question",
    "contact.subject.other": "Other",
    "contact.subject.select": "Select subject...",
    "product.back": "← Back to Products",
    "product.request": "Request a Quote",
    "product.download": "Download Catalog",
    "product.applications": "Applications",
    "product.technical": "Technical Specifications",
    "product.features": "Features",
    "product.models": "Model Range",
    "product.contact_expert": "Contact an Expert",
    "breadcrumb.home": "Home",
    "breadcrumb.products": "Products",
    "gallery.title": "Gallery",
    "gallery.description": "Here we will showcase our work — photos and videos of production, installation and service of equipment.",
    "gallery.photo": "Photo",
    "quick.service.title": "Service",
    "quick.service.desc": "Technical support and maintenance",
    "quick.contact.title": "Contact Person",
    "quick.contact.desc": "Find your account manager",
    "quick.gallery.title": "Gallery",
    "quick.gallery.desc": "View our work",
    "hero.quote_btn": "Request a Quote",
    "hero.catalog_btn": "Product Catalogue",
    "hero.consultation_btn": "Consultation",
    "hero.trust_iso": "ISO 9001:2015",
    "hero.trust_atex": "ATEX",
    "hero.trust_ce": "CE",
    "hero.trust_text": "Certified European Quality",
    "testimonials.title": "CLIENT TESTIMONIALS",
    "testimonial.1.text": "KREI equipment significantly increased our production efficiency. The dispersion quality exceeded our expectations.",
    "testimonial.1.name": "Peter Kovalenko",
    "testimonial.1.company": "Promfarb LLC",
    "testimonial.2.text": "Teon's service and support are top-notch. We recommend them as a reliable partner.",
    "testimonial.2.name": "Andreas Schneider",
    "testimonial.2.company": "Farben GmbH",
    "testimonial.3.text": "High-precision equipment that fully meets our requirements. We especially appreciate the reliability and durability.",
    "testimonial.3.name": "Marta Nowak",
    "testimonial.3.company": "Chemia Sp. z o.o.",
    "stats.machines": "Machines Installed",
    "stats.clients": "Clients",
    "stats.years": "Years Experience",
    "quote.title": "REQUEST A QUOTE",
    "quote.subtitle": "Leave a request and we will send you a commercial offer within 24 hours",
    "quote.name": "Name *",
    "quote.email": "Email *",
    "quote.message": "Message *",
    "quote.send": "Send Request",
    "quote.success": "Thank you for your request!",
    "quote.success.text": "We will contact you shortly.",
    "quote.required": "* Required fields",
    "product.feedback_title": "Get a Consultation",
    "product.feedback_desc": "Leave your contacts — our manager will contact you within 24 hours",
    "product.feedback_name": "Your Name *",
    "product.feedback_phone": "Phone *",
    "product.feedback_email": "Email",
    "product.feedback_comment": "Comment (model, volume, power...)",
    "product.feedback_send": "Send Request",
    "product.feedback_success": "Thank you!",
    "product.feedback_success_text": "We will contact you shortly.",
    "product.feedback_via": "Or contact us directly:",
    "product.media_title": "Real Work Photos & Videos",
    "product.media_desc": "See how KREI equipment works on real production sites",
    "product.media_request": "Request Photos/Videos",
    "product.media_request_text": "Want to see more materials? Send a request and we'll share the details.",
    "product.media_video_title": "Work Video",
    "product.comparison_title": "Model Comparison",
    "home.about_short": "TEON UKRAINE LLC is the official representative of high-quality European Teon equipment in Ukraine. Over 8 years — more than 200 machines and 50+ countries.",
    "home.about_link": "Learn More About the Company",
    "trust.quality": "European Quality",
    "trust.global": "50+ Countries",
    "trust.experience": "8+ Years Experience",
    "trust.certified": "Certified",
  },
  pl: {
    "nav.news": "Aktualności",
    "nav.exhibitions": "Targi",
    "nav.contact_person": "Osoba kontaktowa",
    "nav.worldwide": "Na całym świecie",
    "nav.company": "FIRMA",
    "nav.products": "PRODUKTY",
    "nav.service": "SERWIS",
    "nav.contact": "KONTAKT",
    "nav.quote": "POPROŚ O WYCENĘ",
    "nav.menu": "Menu",
    "search.placeholder": "Szukaj...",
    "search.open": "Otwórz wyszukiwarkę",
    "search.close": "Zamknij wyszukiwarkę",
    "search.submit": "Szukaj",
    "search.title": "Wyniki wyszukiwania",
    "search.for": 'Wyniki dla "{query}"',
    "search.no_results": "Nic nie znaleziono",
    "search.no_results_desc": "Spróbuj zmienić zapytanie lub przejrzyj nasze produkty.",
    "search.browse_products": "Zobacz wszystkie produkty",
    "search.found": "Znaleziono {count} wyników",
    "hero.tagline1": "DYSPERGOWANIE ▪ MIESZANIE ▪ MIELENIE",
    "hero.tagline2": "MASZYNY DLA PRZEMYSŁU LAKIERNICZEGO I CHEMICZNEGO",
    "process.title": "NASZE TECHNOLOGIE",
    "process.dispersing": "Dyspergowanie",
    "process.dispersing.desc": "Efektywne dyspergowanie pigmentów i wypełniaczy w układach ciekłych dla osiągnięcia maksymalnej jakości koloru i stabilności.",
    "process.mixing": "Mieszanie",
    "process.mixing.desc": "Precyzyjne mieszanie wieloskładnikowych receptur zapewniające homogeniczność w całej objętości zbiornika.",
    "process.grinding": "Mielenie",
    "process.grinding.desc": "Dokładne mielenie na mokro do rozmiarów submikronowych dla idealnie gładkich powłok i wysokiej siły krycia.",
    "about.title": "Teon przedstawia się",
    "about.text1": "TEON UKRAINE Sp. z o.o. jest oficjalnym przedstawicielem wysokiej jakości sprzętu Teon na Ukrainie. Dostarczamy pełen zakres rozwiązań do dyspergowania, mieszania i mielenia, a także usług serwisowych dla przemysłu lakierniczego i chemicznego.",
    "about.text2": "W ciągu 8 lat działalności zainstalowaliśmy ponad 200 maszyn, zbudowaliśmy sieć centrów serwisowych i zyskaliśmy zaufanie wiodących przedsiębiorstw na Ukrainie. Naszą misją jest wyposażenie ukraińskiego przemysłu w nowoczesny sprzęt z pełnym wsparciem technicznym.",
    "products.title": "NASZE PRODUKTY",
    "products.more": "Dowiedz się więcej",
    "why.title": "DLACZEGO TEON?",
    "why.since": "Od 2017 roku",
    "why.since.desc": "8+ lat doświadczenia na rynku ukraińskim",
    "why.quality": "Jakość europejska",
    "why.quality.desc": "Najwyższe standardy produkcji i kontroli jakości",
    "why.worldwide": "Na całym świecie",
    "why.worldwide.desc": "Dostawa i serwis w ponad 50 krajach świata",
    "why.innovation": "Innowacje",
    "why.innovation.desc": "Ciągły rozwój i doskonalenie technologii",
    "news.title": "AKTUALNOŚCI",
    "news.all": "Wszystkie aktualności",
    "news.read_more": "Czytaj dalej",
    "exhibitions.title": "TARGI",
    "footer.rights": "© 2024 Teon. Wszelkie prawa zastrzeżone.",
    "company.title": "FIRMA",
    "company.about": "O nas",
    "company.history": "Historia firmy",
    "company.contact_info": "Dane kontaktowe",
    "company.certificates": "Certyfikaty",
    "products.page.title": "PRODUKTY",
    "products.request": "Zapytaj o informacje",
    "products.features": "Cechy:",
    "products.models": "Modele:",
    "service.title": "SERWIS",
    "service.our": "Nasz serwis",
    "service.text": "Firma Teon oferuje pełen zakres usług serwisowych dla swoich urządzeń. Nasi specjaliści są gotowi zapewnić wsparcie na wszystkich etapach — od montażu i uruchomienia po planową konserwację i naprawy.",
    "service.cta": "Potrzebujesz pomocy?",
    "service.cta.text": "Skontaktuj się z naszym działem wsparcia technicznego",
    "service.contact_us": "Skontaktuj się z nami",
    "service.item.install.title": "Montaż i uruchomienie",
    "service.item.install.text": "Wykwalifikowani technicy Teon przeprowadzą montaż i uruchomienie urządzeń w Twoim zakładzie.",
    "service.item.maintenance.title": "Konserwacja",
    "service.item.maintenance.text": "Regularna konserwacja zapewniająca niezawodne działanie urządzeń i maksymalną żywotność.",
    "service.item.repair.title": "Naprawa i regeneracja",
    "service.item.repair.text": "Sprawna naprawa o dowolnym stopniu złożoności z użyciem oryginalnych części zamiennych Teon.",
    "service.item.spares.title": "Części zamienne",
    "service.item.spares.text": "Szeroki asortyment oryginalnych części zamiennych na stanie, szybka dostawa na cały świat.",
    "service.item.training.title": "Szkolenie personelu",
    "service.item.training.text": "Szkolenie operatorów i personelu technicznego u klienta lub w naszym centrum szkoleniowym na Ukrainie.",
    "service.item.support.title": "Wsparcie techniczne",
    "service.item.support.text": "Całodobowe wsparcie techniczne w rozwiązywaniu wszelkich problemów przez telefon lub online.",
    "contact.title": "KONTAKT",
    "contact.info": "Dane kontaktowe",
    "contact.write": "Napisz do nas",
    "contact.name": "Imię i nazwisko *",
    "contact.company": "Firma",
    "contact.email": "Email *",
    "contact.phone": "Telefon",
    "contact.subject": "Temat *",
    "contact.message": "Wiadomość *",
    "contact.send": "Wyślij wiadomość",
    "contact.success": "Dziękujemy za wiadomość!",
    "contact.success.text": "Skontaktujemy się z Tobą w najbliższym czasie roboczym.",
    "contact.required": "* Pola wymagane",
    "contact.subject.product": "Zapytanie o produkt",
    "contact.subject.service": "Zapytanie serwisowe",
    "contact.subject.parts": "Części zamienne",
    "contact.subject.general": "Ogólne pytanie",
    "contact.subject.other": "Inne",
    "contact.subject.select": "Wybierz temat...",
    "product.back": "← Powrót do produktów",
    "product.request": "Zapytaj o ofertę",
    "product.download": "Pobierz katalog",
    "product.applications": "Zastosowania",
    "product.technical": "Dane techniczne",
    "product.features": "Cechy szczególne",
    "product.models": "Seria modeli",
    "product.contact_expert": "Skontaktuj się z ekspertem",
    "breadcrumb.home": "Strona główna",
    "breadcrumb.products": "Produkty",
    "gallery.title": "Galeria",
    "gallery.description": "Tutaj zaprezentujemy nasze realizacje, zdjęcia i filmy z produkcji, montażu i serwisu urządzeń.",
    "gallery.photo": "Zdjęcie",
    "quick.service.title": "Serwis",
    "quick.service.desc": "Wsparcie techniczne i konserwacja",
    "quick.contact.title": "Osoba kontaktowa",
    "quick.contact.desc": "Znajdź swojego opiekuna",
    "quick.gallery.title": "Galeria",
    "quick.gallery.desc": "Zobacz nasze realizacje",
    "hero.quote_btn": "Poproś o wycenę",
    "hero.catalog_btn": "Katalog produktów",
    "hero.consultation_btn": "Konsultacja",
    "hero.trust_iso": "ISO 9001:2015",
    "hero.trust_atex": "ATEX",
    "hero.trust_ce": "CE",
    "hero.trust_text": "Certyfikowana niemiecka jakość",
    "testimonials.title": "OPINIE KLIENTÓW",
    "testimonial.1.text": "Urządzenia KREI znacząco zwiększyły wydajność naszej produkcji. Jakość dyspergowania przekroczyła nasze oczekiwania.",
    "testimonial.1.name": "Piotr Kowalenko",
    "testimonial.1.company": "Promfarb Sp. z o.o.",
    "testimonial.2.text": "Serwis i wsparcie Teon są na najwyższym poziomie. Polecamy jako niezawodnego partnera.",
    "testimonial.2.name": "Andreas Schneider",
    "testimonial.2.company": "Farben GmbH",
    "testimonial.3.text": "Precyzyjne urządzenia, które w pełni spełniają nasze wymagania. Szczególnie cenimy niezawodność i trwałość.",
    "testimonial.3.name": "Marta Nowak",
    "testimonial.3.company": "Chemia Sp. z o.o.",
    "stats.machines": "Zainstalowanych maszyn",
    "stats.clients": "Klientów",
    "stats.years": "Lat doświadczenia",
    "quote.title": "POPROŚ O WYCENĘ",
    "quote.subtitle": "Zostaw zapytanie, a wyślemy Ci ofertę handlową w ciągu 24 godzin",
    "quote.name": "Imię i nazwisko *",
    "quote.email": "Email *",
    "quote.message": "Wiadomość *",
    "quote.send": "Wyślij zapytanie",
    "quote.success": "Dziękujemy za zapytanie!",
    "quote.success.text": "Skontaktujemy się z Tobą wkrótce.",
    "quote.required": "* Pola wymagane",
    "product.feedback_title": "Uzyskaj konsultację",
    "product.feedback_desc": "Zostaw swoje dane kontaktowe — nasz menedżer skontaktuje się z Tobą w ciągu 24 godzin",
    "product.feedback_name": "Imię i nazwisko *",
    "product.feedback_phone": "Telefon *",
    "product.feedback_email": "Email",
    "product.feedback_comment": "Komentarz (model, objętość, moc...)",
    "product.feedback_send": "Wyślij zapytanie",
    "product.feedback_success": "Dziękujemy!",
    "product.feedback_success_text": "Skontaktujemy się z Tobą wkrótce.",
    "product.feedback_via": "Lub skontaktuj się z nami bezpośrednio:",
    "product.media_title": "Zdjęcia i filmy z rzeczywistej pracy",
    "product.media_desc": "Zobacz, jak urządzenia KREI pracują na rzeczywistych halach produkcyjnych",
    "product.media_request": "Poproś o zdjęcia/filmy",
    "product.media_request_text": "Chcesz zobaczyć więcej materiałów? Wyślij zapytanie, a my podzielimy się szczegółami.",
    "product.media_video_title": "Film z pracy",
    "product.comparison_title": "Porównanie modeli",
    "home.about_short": "TEON UKRAINE Sp. z o.o. jest oficjalnym przedstawicielem wysokiej jakości europejskiego sprzętu Teon na Ukrainie. Ponad 200 maszyn i 50+ krajów w ciągu 8 lat.",
    "home.about_link": "Dowiedz się więcej o firmie",
    "trust.quality": "Jakość europejska",
    "trust.global": "Ponad 50 krajów",
    "trust.experience": "8+ lat doświadczenia",
    "trust.certified": "Certyfikowane",
  },
};